# Generated by Django 5.0.1 on 2024-02-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='llm_config',
            new_name='_llm_config',
        ),
    ]
