# Generated by Django 5.0.1 on 2024-02-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_llmconfig_config_list_llmconfig_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='api_key',
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='api_keys',
            field=models.ManyToManyField(to='agents.apikey'),
        ),
    ]
