# Generated by Django 5.0.1 on 2024-02-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_apikey_remove_llmconfig_api_key_llmconfig_api_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='model',
        ),
    ]
