# Generated by Django 5.0.1 on 2024-02-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_rename_value_apikey__value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='llm_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.llmconfig'),
        ),
    ]
