# Generated by Django 5.0.1 on 2024-02-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_agent_llm_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='_is_termination_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='human_input_mode',
            field=models.CharField(choices=[('NEVER', 'NEVER'), ('ALWAYS', 'ALWAYS'), ('TERMINATE', 'TERMINATE')], default='ALWAYS', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_consecutive_reply',
            field=models.IntegerField(default=0),
        ),
    ]
