# Generated by Django 5.0.1 on 2024-02-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_remove_llmconfig_use_docker'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='use_docker',
            field=models.BooleanField(default=False),
        ),
    ]
