# Generated by Django 5.0.1 on 2024-02-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agent_use_docker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='_code_execution_config',
            new_name='use_code_execution',
        ),
    ]
