# Generated by Django 5.0.1 on 2024-02-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_rename__code_execution_config_agent_use_code_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='max_consecutive_reply',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='use_code_execution',
            field=models.BooleanField(default=False),
        ),
    ]
