# Generated by Django 5.0.1 on 2024-04-18 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_trainingsource_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
