# Generated by Django 5.0.1 on 2024-02-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
