# Generated by Django 5.0.1 on 2024-04-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WriterTrainingSet',
        ),
    ]
